### PR TITLE
Update master to state at the end of Run 2

### PR DESCRIPTION
**Pull request by guitargeek**
When I looked at the workflow descriptions for EGM Tag and probe for all year in Run 2 [1], I realized that the development of this package basically diverged into three branches for the 3 data taking years:

* 2016: https://github.com/swagata87/EgammaAnalysis-TnPTreeProducer/tree/IDv2_2016sample_miniaod
* 2017: https://github.com/swagata87/EgammaAnalysis-TnPTreeProducer/tree/IDv2_2017sample
* 2018: https://github.com/lsoffi/EgammaAnalysis-TnPTreeProducer/tree/v2018.09.24_10_2_X_prelim

For someone who want's to stick to the Egamma recipes as close as possible, but also wants to add some new variable to the TnPTree, it's a bit annoying because it's not really clear what the differences between these branches is and I have to repeat work for all 3. Maybe it would be good to fast forward the actual master branch to a kind of lowest common denominator as a first step to combat this divergence?

The 2016 and 2017 branches are already very similar in git history and only differ by their last two commits. As a start, I suggest here to merge the common part or their git history to this master branch.

The 2018 branch just has one huge commit on top of the cms-analysis master branch which brings it very close to the 2016 and 2017 branches, so the divergence there is not as bad as it looks. Actually, the only difference between the 3 branches are more or less all contained in the following files:

* python/TnPTreeProducer_cfg.py
* python/etc/tnpInputTestFiles_cff.py
* the submit files in scripts/crab

So maybe after this initial fast forwarding one could think of putting versions of these files for each year in the master branch here and then there is an end to the divergence?

This PR is just a suggestion because I think it would make maintaining this TnPTreeProducer tool significantly easier. Who is responsible for maintaining this cms-analysis repository actually?

To notify the EGM ID conveners: @swagata87 @michelif 

[1] https://twiki.cern.ch/twiki/bin/view/CMSPublic/ElectronTagAndProbe

### CODE REVIEW

**Comment by michelif** [comment]
hi jonas,
great! i agree with you that having a fast-forward in the master and then adapt those three files would be way better than the actual workflow. i support it, but i am not anymore the ID convener, I add here in cc  livia and shilpi (i don't have the github account of the new convener, ashim but they should). thanks a lot for this.
@lsoffi @jainshilpi

**Comment by swagata87** [comment]
The suggestion looks good to me, and it can be merged. The actual code for 3 years is very similar. I remember we did some changes in 2018 just to check a few things (Nm1 branch in my repo), but those changes are not specific to any year, so can be used for 2016+17 also. Having those changes is not mandatory anyway. So in general it is good to have one version of code for full Run2. I do not have permission to merge this PR though; and I am not sure who can do it, may be @jainshilpi or @lsoffi ?

**Comment by jainshilpi** [comment]
@swagata87 if you can create a PR, which is common to all the 2 years I think I can merge.

**Comment by swagata87** [comment]
can you merge Jonas's PR? This looks good.

**Comment by jainshilpi** [comment]
ah, no I dont the powers. I just realized this is cms-analysis and not cms-egamma.

**Comment by michelif** [comment]
hi shilpi, i think you have to ask fabrice to add you to the organization

**Comment by guitargeek** [comment]
Hello @jainshilpi, could you figure out how to get the rights to merge? Or maybe @fcouderc would be ok to do it this time? I still think it would be quite nice to update the original repo.

**Comment by jainshilpi** [comment]
hi @guitargeek , apologies for missing this. Indeed, @fcouderc I think you have the rights to add me to the organization so that I can merge such requests. Could you please add me and if you could merge this one from Jonas? thanks

**Comment by guitargeek** [comment]
Hi @jainshilpi, @fcouderc just a little reminder. I'm worried that people feel discouraged from contributing to these tools (e.g. adding variables for their studies) if the master repo and branch situation is so uncertain.

**Comment by fcouderc** [comment]
Hi all,

since I am not EGM anymore since several years already, I have to say that I never checked this messages carefully. Sorry about that, I will merge this. But we need to add the actual EGM group as responsible for these things !

**Pull request merged**
